export const dataMap = [

  { raceName: "Весенний Турмарафон 2017",
    id: 1,
    ddate: '2017-04-22',
    needLoad: false,
    sname: "Весенний",
    location: "Ерденево",
    distances: [
      {fullName: "Весенний ТМ 2017, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: ""
      },
      {fullName: "Весенний ТМ 2017, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: ""
      },
      {fullName: "Весенний ТМ 2017, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: ""
      },
    ],
  },
  { raceName: "Летний Турмарафон 2017",
    id: 2,
    ddate: '2017-07-22',
    needLoad: false,
    sname: "Летний",
    location: "Шаховская",
    distances: [
      {fullName: "Летний ТМ 2017, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2017_25.txt"
      },
      {fullName: "Летний ТМ 2017, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 500,
        fileName: "лето2017_50.txt"
      },
      {fullName: "Летний ТМ 2017, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "лето2017_100.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2017",
    id: 3,
    ddate: '2017-10-07',
    needLoad: false,
    sname: "Осенний",
    location: "Конев бор",
    distances: [
      {fullName: "Осенний ТМ 2017, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2017_25.txt"
      },
      {fullName: "Осенний ТМ 2017, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "осень2017_50.txt"
      },
      {fullName: "Осенний ТМ 2017, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "осень2017_100.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2017",
    id: 4,
    ddate: '2017-12-09',
    needLoad: false,
    sname: "Зимний",
    location: "Заокский",
    distances: [
      {fullName: "Зимний ТМ 2017, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "зима2017_25.txt"
      },
      {fullName: "Зимний ТМ 2017, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "зима2017_50.txt"
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2018",
    id: 5,
    ddate: '2018-04-14',
    needLoad: false,
    sname: "Весенний",
    location: "Балакирево",
    distances: [
      {fullName: "Весенний ТМ 2018, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2018_25.txt"
      },
      {fullName: "Весенний ТМ 2018, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2018_50.txt"
      },
    ],
  },
  { raceName: "Летний Турмарафон 2018",
    id: 6,
    ddate: '2018-07-15',
    needLoad: false,
    sname: "Летний",
    location: "Кузяево",
    distances: [
      {fullName: "Летний ТМ 2018, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2018_25.txt"
      },
      {fullName: "Летний ТМ 2018, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "лето2018_50.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2018",
    id: 7,
    ddate: '2018-10-06',
    needLoad: true,
    sname: "Осенний",
    location: "Верея",
    distances: [
      {fullName: "Осенний ТМ 2018, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2018_25.txt"
      },
      {fullName: "Осенний ТМ 2018, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "осень2018_50.txt"
      },
      {fullName: "Осенний ТМ 2018, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "осень2018_100.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2018",
    id: 8,
    ddate: '2018-12-08',
    needLoad: true,
    sname: "Зимний",
    location: "Лесодолгоруково",
    distances: [
      {fullName: "Зимний ТМ 2018, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "зима2018_25.txt"
      },
      {fullName: "Зимний ТМ 2018, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "зима2018_50.txt"
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2019",
    id: 9,
    ddate: '2019-04-20',
    needLoad: true,
    sname: "Весенний",
    location: "Узуново",
    distances: [
      {fullName: "Весенний ТМ 2019, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2019_25.txt"
      },
      {fullName: "Весенний ТМ 2019, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2019_50.txt"
      },
      {fullName: "Весенний ТМ 2019, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "весна2019_100.txt"
      },
    ],
  },
  { raceName: "Летний Турмарафон 2019",
    id: 10,
    ddate: '2019-07-20',
    needLoad: true,
    sname: "Летний",
    location: "Сушнево",
    distances: [
      {fullName: "Летний ТМ 2019, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2019_25.txt"
      },
      {fullName: "Летний ТМ 2019, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "лето2019_55.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2019",
    id: 11,
    ddate: '2019-10-05',
    needLoad: true,
    sname: "Осенний",
    location: "Донховка",
    distances: [
      {fullName: "Осенний ТМ 2019, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2019_25.txt"
      },
      {fullName: "Осенний ТМ 2019, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "осень2019_55.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2019",
    id: 12,
    ddate: '2019-12-07',
    needLoad: true,
    sname: "Зимний",
    location: "Шаликово",
    distances: [
      {fullName: "Осенний ТМ 2019, 27km Lite",
        name: "27km Lite",
        courseType: "lite",
        km: 27,
        fileName: "зима2019_27.txt"
      },
      {fullName: "Осенний ТМ 2019, 57km Tourist",
        name: "57km Tourist",
        courseType: "tourist",
        km: 57,
        fileName: "зима2019_57.txt"
      },
    ],
  },
  { raceName: "Лыжный Турмарафон 2020",
    id: 13,
    ddate: '2020-02-15',
    needLoad: true,
    sname: "Лыжный",
    location: "Лесодолгоруково",
    distances: [
      {fullName: "Лыжный ТМ 2020, 15km Lite",
        name: "15km Lite",
        courseType: "lite",
        km: 15,
        fileName: "лыжный2020_15.txt"
      },
      {fullName: "Лыжный ТМ 2020, 30km Tourist",
        name: "30km Tourist",
        courseType: "tourist",
        km: 30,
        fileName: "лыжный2020_30.txt"
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2020",
    id: 14,
    ddate: '2020-04-18',
    needLoad: true,
    sname: "Весенний",
    location: "Жилёво",
    distances: [
      {fullName: "Весенний ТМ 2020, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2020_25.txt"
      },
      {fullName: "Весенний ТМ 2020, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2020_50.txt"
      },
    ],
  },
  { raceName: "Летний Турмарафон 2020",
    id: 15,
    ddate: '2020-07-18',
    needLoad: true,
    sname: "Летний",
    location: "Хотьково",
    distances: [
      {fullName: "Летний ТМ 2020, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2020_25.txt"
      },
      {fullName: "Летний ТМ 2020, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "лето2020_50.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2020",
    id: 16,
    ddate: '2020-10-03',
    needLoad: true,
    sname: "Осенний",
    location: "Воиново",
    distances: [
      {fullName: "Осенний ТМ 2020, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2020_25.txt"
      },
      {fullName: "Осенний ТМ 2020, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "осень2020_50.txt"
      },
      {fullName: "Осенний ТМ 2020, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "осень2020_100.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2020",
    id: 17,
    ddate: '2020-12-12',
    needLoad: true,
    sname: "Зимний",
    location: "Ямуга",
    distances: [
      {fullName: "Зимний ТМ 2020, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "зима2020_25.txt"
      },
      {fullName: "Зимний ТМ 2020, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "зима2020_50.txt"
      },
    ],
  },
  { raceName: "Лыжный Турмарафон 2021",
    id: 18,
    ddate: '2021-02-13',
    needLoad: true,
    sname: "Лыжный",
    location: "Балакирево",
    distances: [
      {fullName: "Лыжный ТМ 2021, 20km Lite",
        name: "20km Lite",
        courseType: "lite",
        km: 20,
        fileName: "лыжный2021_20.txt"
      },
      {fullName: "Лыжный ТМ 2021, 44km Tourist",
        name: "44km Tourist",
        courseType: "tourist",
        km: 44,
        fileName: "лыжный2021_44.txt"
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2021",
    id: 19,
    ddate: '2021-04-17',
    needLoad: true,
    sname: "Весенний",
    location: "Суходрев",
    distances: [
      {fullName: "Весенний ТМ 2021, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2021_25.txt"
      },
      {fullName: "Весенний ТМ 2021, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2021_50.txt"
      },
      {fullName: "Весенний ТМ 2021, 100km Ultra",
        name: "100km Ultra",
        courseType: "ultra",
        km: 100,
        fileName: "весна2021_100.txt"
      },
    ],
  },
  { raceName: "наСТОящий Турмарафон 2021",
    id: 20,
    ddate: '2021-05-29',
    needLoad: true,
    sname: "наСТОящий",
    location: "Петушки-Черусти",
    distances: [
      {fullName: "НаСТОящий ТМ 2021, 100km real",
        name: "100km Real",
        courseType: "real",
        km: 100,
        fileName: "настоящий2021.txt"
      },
    ],
  },
  { raceName: "Летний Турмарафон 2021",
    id: 21,
    ddate: '2021-07-17',
    needLoad: true,
    sname: "Летний",
    location: "Жилёво",
    distances: [
      {fullName: "Летний ТМ 2021, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2021_25.txt"
      },
      {fullName: "Летний ТМ 2021, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "лето2021_50.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2021",
    id: 22,
    ddate: '2021-10-02',
    needLoad: true,
    sname: "Осенний",
    location: "Москворецкая",
    distances: [
      {fullName: "Осенний ТМ 2021, 30km Lite",
        name: "30km Lite",
        courseType: "lite",
        km: 30,
        fileName: "осень2021_30.txt"
      },
      {fullName: "Осенний ТМ 2021, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "осень2021_55.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2021",
    id: 23,
    ddate: '2021-12-11',
    needLoad: true,
    sname: "Зимний",
    location: "Темпы",
    distances: [
      {fullName: "Зимний ТМ 2021, 30km Lite",
        name: "30km Lite",
        courseType: "lite",
        km: 30,
        fileName: "зима2021_30.txt"
      },
      {fullName: "Зимний ТМ 2021, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "зима2021_50.txt"
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2022",
    id: 24,
    ddate: '2022-04-23',
    needLoad: true,
    sname: "Весенний",
    location: "Боровск",
    distances: [
      {fullName: "Весенний ТМ 2022, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2022_25.txt"
      },
      {fullName: "Весенний ТМ 2022, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2022_50.txt",
      },
      {fullName: "Весенний ТМ 2022, 75km Ultra",
        name: "75km Ultra",
        courseType: "ultra",
        km: 75,
        fileName: "весна2022_75.txt",
      },
    ],
  },
  { raceName: "Летний Турмарафон 2022",
    id: 25,
    ddate: '2022-07-16',
    needLoad: true,
    sname: "Летний",
    location: "Грибово",
    distances: [
      {fullName: "Летний ТМ 2022, 30km Lite",
        name: "30km Lite",
        courseType: "lite",
        km: 30,
        fileName: "лето2022_30.txt"
      },
      {fullName: "Летний ТМ 2022, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "лето2022_55.txt",
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2022",
    id: 26,
    ddate: '2022-10-08',
    needLoad: true,
    sname: "Осенний",
    location: "Звенигород",
    distances: [
      {fullName: "Осенний ТМ 2022, 30km Lite",
        name: "30km Lite",
        courseType: "lite",
        km: 30,
        fileName: "осень2022_30.txt"
      },
      {fullName: "Осенний ТМ 2022, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "осень2022_55.txt",
      },
      {fullName: "Осенний ТМ 2022, 75km Ultra",
        name: "75km Ultra",
        courseType: "ultra",
        km: 75,
        fileName: "осень2022_75.txt",
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2022",
    id: 27,
    ddate: '2022-12-10',
    needLoad: true,
    sname: "Зимний",
    location: "Запутная",
    distances: [
      {fullName: "Зимний ТМ 2022, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "зима2022_25.txt"
      },
      {fullName: "Зимний ТМ 2022, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "зима2022_50.txt",
      },
    ],
  },
  { raceName: "Лыжный Турмарафон 2023",
    id: 28,
    ddate: '2023-02-18',
    needLoad: true,
    sname: "Лыжный",
    location: "Донховка",
    distances: [
      {fullName: "Лыжный ТМ 2023, 20km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лыжный2023_20.txt"
      },
      {fullName: "Лыжный Турмарафон 2023 30km Tourist",
        name: "30km Tourist",
        courseType: "tourist",
        km: 30,
        fileName: "лыжный2023_30.txt",
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2023",
    id: 29,
    ddate: '2023-04-22',
    needLoad: true,
    sname: "Весенний",
    location: "Пущино",
    distances: [
      {fullName: "Весенний ТМ 2023, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2023_25.txt"
      },
      {fullName: "Весенний ТМ 2023, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2023_50.txt",
      },
      {fullName: "Весенний ТМ 2023, 75km Ultra",
        name: "75km Ultra",
        courseType: "ultra",
        km: 75,
        fileName: "весна2023_75.txt",
      },
    ],
  },
  { raceName: "наСТОящий Турмарафон 2023",
    id: 30,
    ddate: '2023-05-27',
    needLoad: true,
    sname: "наСТОящий",
    location: "Белоомут - Шатурторф",
    distances: [
      {fullName: "наСТОящий ТМ 2023, 100km",
        name: "100km",
        courseType: "real",
        km: 100,
        fileName: "настоящий2023.txt"
      },

    ],
  },
  { raceName: "Летний Турмарафон 2023",
    id: 31,
    ddate: '2023-07-15',
    needLoad: true,
    sname: "Летний",
    location: "Погорелое Городище",
    distances: [
      {fullName: "Летний ТМ 2023, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2023_25.txt"
      },
      {fullName: "Летний ТМ 2023, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "лето2023_50.txt",
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2023",
    id: 32,
    ddate: '2023-10-14',
    needLoad: true,
    sname: "Осенний",
    location: "Вербилки",
    distances: [
      {fullName: "Осенний ТМ 2023, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2023_25.txt"
      },
      {fullName: "Осенний ТМ 2023, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "осень2023_50.txt",
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2023",
    id: 33,
    ddate: '2023-12-09',
    needLoad: true,
    sname: "Зимний",
    location: "Башкино",
    distances: [
      {fullName: "Зимний Турмарафон 2023 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "зима2023_25.txt"
      },
      {fullName: "Зимний Турмарафон 2023 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "зима2023_55.txt",
      },
    ],
  },
  { raceName: "Лыжный Турмарафон 2024",
    id: 34,
    ddate: '2024-02-17',
    needLoad: true,
    sname: "Лыжный",
    location: "Запутная",
    distances: [
      {fullName: "Лыжный ТМ 2024, 20km Lite",
        name: "20km Lite",
        courseType: "lite",
        km: 20,
        fileName: "лыжный2024_20.txt"
      },
      {fullName: "Лыжный ТМ 2024, 40km Tourist",
        name: "40km Tourist",
        courseType: "tourist",
        km: 40,
        fileName: "лыжный2024_40.txt",
      },
    ],
  },
  { raceName: "Весенний Турмарафон 2024",
    id: 35,
    ddate: '2024-04-20',
    needLoad: true,
    sname: "Весенний",
    location: "Шеметово (Ясногорск)",
    distances: [
      {fullName: "Весенний ТМ 2024, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "весна2024_25.txt"
      },
      {fullName: "Весенний ТМ 2024, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "весна2024_50.txt",
      },
      {fullName: "Весенний ТМ 2024, 75km Ultra",
        name: "75km Ultra",
        courseType: "ultra",
        km: 75,
        fileName: "весна2024_75.txt",
      },
    ],
  },
  { raceName: "наСТОящий Турмарафон 2024",
    id: 36,
    ddate: '2024-06-01',
    needLoad: true,
    sname: "наСТОящий",
    location: "Головино - Шатурторф",
    distances: [
      {fullName: "наСТОящий ТМ 2024, 100km",
        name: "100km",
        courseType: "real",
        km: 100,
        fileName: "настоящий2024.txt"
      },
    ],
  },
  { raceName: "Летний Турмарафон 2024",
    id: 37,
    ddate: '2024-07-13',
    needLoad: true,
    sname: "Летний",
    location: "",
    distances: [
      {fullName: "Летний ТМ 2025, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "лето2024_25.txt"
      },
      {fullName: "Летний ТМ 2024, 50km Tourist",
        name: "50km Tourist",
        courseType: "tourist",
        km: 50,
        fileName: "лето2024_50.txt"
      },
    ],
  },
  { raceName: "Осенний Турмарафон 2024",
    id: 38,
    ddate: '2024-10-05',
    needLoad: true,
    sname: "Осенний",
    location: "",
    distances: [
      {fullName: "Осенний ТМ 2025, 25km Lite",
        name: "25km Lite",
        courseType: "lite",
        km: 25,
        fileName: "осень2024_25.txt"
      },
      {fullName: "Осенний ТМ 2024, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "осень2024_55.txt"
      },
    ],
  },
  { raceName: "Зимний Турмарафон 2024",
    id: 39,
    ddate: '2024-12-07',
    needLoad: false,
    sname: "Зимний",
    location: "",
    distances: [
      {fullName: "Зимний ТМ 2024, 28km Lite",
        name: "28km Lite",
        courseType: "lite",
        km: 28,
        fileName: "зима2024_28.txt"
      },
      {fullName: "Зимний ТМ 2024, 55km Tourist",
        name: "55km Tourist",
        courseType: "tourist",
        km: 55,
        fileName: "зима2024_55.txt"
      },
    ],
  },
  { raceName: "безЛыжный Турмарафон 2025",
    id: 40,
    ddate: '2025-02-15',
    needLoad: false,
    sname: "безЛыжный",
    location: "",
    distances: [
      {fullName: "безЛыжный ТМ 2025, 28km Lite",
        name: "12km Easy",
        courseType: "easy",
        km: 12,
        fileName: "безлыжный2025_12.txt"
      },
      {fullName: "безЛыжный ТМ 2025, 55km Tourist",
        name: "24km Lite",
        courseType: "lite",
        km: 24,
        fileName: "безлыжный2025_24.txt"
      },
      {fullName: "безЛыжный ТМ 2025, 55km Tourist",
        name: "35km Tourist",
        courseType: "tourist",
        km: 35,
        fileName: "безлыжный2025_35.txt"
      },
    ],
  },



];
